/* ellen pinto
a22604505
turma02
25/09/2026*/

SELECT EMPLOYEE_ID, CONCAT(UPPER(LAST_NAME),',',' ',first_name)AS formal_name FROM HR.EMPLOYEES;
SELECT EMPLOYEE_ID, CONCAT(LOWER(EMAIL),'@example.org') AS email_address FROM HR.EMPLOYEES;
SELECT LAST_NAME, LEN(LAST_NAME) AS last_name_length FROM HR.EMPLOYEES ORDER BY last_name_length DESC, LAST_NAME ASC;
SELECT EMPLOYEE_ID, SALARY, SALARY * 3 AS quaarter_salary, SALARY * 14 AS annual_salary FROM HR.EMPLOYEES;
SELECT EMPLOYEE_ID, HIRE_DATE, DATEADD(month,6,HIRE_DATE) AS review_date FROM HR.EMPLOYEES;
SELECT EMPLOYEE_ID, COMMISSION_PCT FROM HR.EMPLOYEES WHERE COMMISSION_PCT IS NOT NULL;
