/* ellen pinto
a22604505
turma02
25/09/2026*/

/*A*/
SELECT EMPLOYEE_ID, CONCAT(UPPER(LAST_NAME),',',' ',first_name)AS formal_name FROM HR.EMPLOYEES;
SELECT EMPLOYEE_ID, CONCAT(LOWER(EMAIL),'@example.org') AS email_address FROM HR.EMPLOYEES;
SELECT LAST_NAME, LEN(LAST_NAME) AS last_name_length FROM HR.EMPLOYEES ORDER BY last_name_length DESC, LAST_NAME ASC;
SELECT EMPLOYEE_ID, SALARY, SALARY * 3 AS quaarter_salary, SALARY * 14 AS annual_salary FROM HR.EMPLOYEES;
SELECT EMPLOYEE_ID, HIRE_DATE, DATEADD(month,6,HIRE_DATE) AS review_date FROM HR.EMPLOYEES;
/*B*/
SELECT EMPLOYEE_ID, COMMISSION_PCT FROM HR.EMPLOYEES WHERE COMMISSION_PCT IS NOT NULL;
SELECT EMPLOYEE_ID, SALARY, ISNULL(COMMISSION_PCT,0), SALARY * ISNULL(COMMISSION_PCT, 0) AS commission_amount FROM HR.EMPLOYEES 
SELECT EMPLOYEE_ID, SALARY * 14 + ISNULL(COMMISSION_PCT,0) * 14 annual_total FROM HR.EMPLOYEES ORDER BY annual_total DESC;
SELECT EMPLOYEE_ID, 
       CASE 
            WHEN MANAGER_ID IS NULL THEN 'no manager'
            Else CAST(MANAGER_ID AS VARCHAR(10))
        END AS manager_label
FROM HR.EMPLOYEES;

/*C*/

SELECT EMPLOYEE_ID, 
        CASE 
            WHEN DEPARTMENT_ID IS NULL THEN 'DEPT-UNASSIGNED'
            ELSE CAST(DEPARTMENT_ID AS VARCHAR(10))
        END AS department_code
FROM HR.EMPLOYEES;

SELECT EMPLOYEE_ID, CONVERT(CHAR(10),HIRE_DATE,23) AS iso_hire_date FROM HR.EMPLOYEES;

